Create portfolio desktop version
Lornakaboro/Lorna-s-portfolio pull request #5
Opened 2022-11-03 18:57 UTC by Lornakaboro

## For this project  I :

- Worked on the desktop version of my portfolio project
- Used media queries to make sure that the web page is displayed correctly on desktop screens .
- Checked for linter errors and ensured that the mobile version of my portfolio project was working just as effectively.

2022-11-03 21:26 UTC, Debas-31 requested changes
> ## Hi @Lornakaboro  :wave:
# Status: Required Change :recycle:
Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights 
- PR title and summary :heavy_check_mark: 
- Commit message :heavy_check_mark:
- Project functionality :heavy_check_mark: 


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 21:26 UTC, Debas-31 commented on style.css
> +    width: 78%;
- [ ] Make sure when we use a mobile-first approach, screen size is designed based on mobile-first, so the media query min-width instead of max-width. For the desktop version, please use a `min-width` in the range of 768 px to 1440 px. Please fix this :wrench:  

***[Video demonstration of your design](https://drive.google.com/file/d/10o-uQ_uiUgxLMo656X1t9ylIQ5F9sfNM/view?usp=sharing)***

 - ***About section***
 
| Figma design | Your design |
|-------------------|-------------------|
| ![Screenshot from 2022-11-03 22-34-51](https://user-images.githubusercontent.com/65129228/199831680-e61e3dcd-bdfd-42da-88f7-a13e8a3d3c96.png) | ![Screenshot from 2022-11-03 22-40-48](https://user-images.githubusercontent.com/65129228/199831752-4fabf984-988b-4fef-bc8c-b48cd66ed7a7.png) |

- [ ] Please ensure the hamburger menu icon is not visible in the desktop version. :+1: 

- ***Work section***

| Figma design | Your design |
|-------------------|-------------------|
| ![Screenshot from 2022-11-03 22-46-59](https://user-images.githubusercontent.com/65129228/199833276-61f544dc-7e5b-4c7e-a1dd-c1ed1ec6a890.png) | ![Screenshot from 2022-11-03 22-46-24](https://user-images.githubusercontent.com/65129228/199833382-29071842-69bd-4980-b780-1f58c8bd9c85.png)|

- ***About-me section***

| Figma design | Your design |
|-------------------|-------------------|
| ![Screenshot from 2022-11-03 22-47-59](https://user-images.githubusercontent.com/65129228/199833690-b01b7646-7414-4891-aca4-b7502393fa99.png) | ![Screenshot from 2022-11-03 22-48-57](https://user-images.githubusercontent.com/65129228/199833770-6d85a2ef-c7fa-4059-b98e-c0367fc492a3.png) |

- ***Contact section***

| Figma design | Your design |
|-------------------|-------------------|
| ![Screenshot from 2022-11-03 22-48-29](https://user-images.githubusercontent.com/65129228/199834017-bd201707-1c8e-4e59-bce2-c484e90659f3.png) | ![Screenshot from 2022-11-03 22-49-37](https://user-images.githubusercontent.com/65129228/199834122-689f88d8-9ab1-45be-ab12-595dcfee1caa.png) |

2022-11-03 21:26 UTC, Debas-31 commented on style.css
> +    display: none;
- [ ] Make sure when we use a mobile-first approach, screen size is designed based on mobile-first, so the media query  `min-width` instead of  ` max-width. ` That is why your design effect is in the mobile version. Please fix this :wrench: 

***Your design***
![Screenshot from 2022-11-03 22-19-51](https://user-images.githubusercontent.com/65129228/199828857-eba502b5-05cc-48f4-a8b7-f0b5dbd1a420.png)

- [ ] Please ensure the hamburger menu is present in your mobile design :+1:

2022-11-04 17:59 UTC, Lizdev-05 requested changes
Hi @Lornakaboro, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- PR title and summary ✔️
- Commit message ✔️
- Project functionality ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 17:59 UTC, Lizdev-05 commented on index.html
> +  </section>
Great work @Lornakaboro 👍,  just like the previous code reviewer stated, kindly minimize your card's height to  meet up with the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1)


**Figma Design**![Figma Design](https://user-images.githubusercontent.com/73854999/200043025-1788d0a9-6baf-4591-96b7-7a1790db677e.png)  

**Your Design**![Your design](https://user-images.githubusercontent.com/73854999/200043112-3bba423f-a3de-412f-b674-32bb37873a00.png)

2022-11-04 17:59 UTC, Lizdev-05 commented on index.html
> +              placeholder ="enter username" required="required" maxlength="30" >
Kindly check the styling of the contact form, there is an empty space before the form, and also the text is not showing ☺. 
![empty-space](https://user-images.githubusercontent.com/73854999/200043908-bb107ec6-2820-4c6b-b8a9-7cac8a37771c.PNG)

2022-11-04 18:40 UTC, OyePriscilla approved these changes
## Hi @Lornakaboro   :smiley: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Descriptive pull request message :heavy_check_mark: 
Linter error checks validated :heavy_check_mark: 
Commit messages are meaningful. :heavy_check_mark: 
GitHub flow observed ✔️ 

## Optional suggestions

- [optional] Kindly ensure you remove the unnecessary lines for your work to be neat. 👍 

## Your design
![b14](https://user-images.githubusercontent.com/103386183/200048166-b85eecb7-fb83-493e-b808-62f4279bafbd.png)

- [ optional] Add margin bottom to this button element as well according to the template. 😃 
 
![b15](https://user-images.githubusercontent.com/103386183/200051059-7ea8e603-78cc-421d-b113-69119e392e84.png)



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 19:08 UTC, merged